### ISSUE TITLE
Is it working or not?

### ISSUE THREAD

**Issue by xeiki** [jshackles/idle_master_py#39]
Hey,
I'm using Idle Master on Windows and have no problems at all there.
Now I have read here that we can use Idle Master on Linux too, so I'm trying it.
I have installed everything and put the cookie stuff on the settings.txt and get it some kind of working?
I just dont know if its now working correctly or not?
I'm getting this output on ssh.

Using Linux Debian 8 64bit
```
user@home:/home/idle_master_py/Releases/Linux# python2 start.py
[ 06/15/2017 02:53:38 AM ] WELCOME TO IDLE MASTER
[ 06/15/2017 02:53:38 AM ] Finding games that have card drops remaining
[ 06/15/2017 02:53:39 AM ] Reading badge page, please wait
[ 06/15/2017 02:53:39 AM ] No games have been blacklisted
[ 06/15/2017 02:53:39 AM ] Idle Master needs to idle 2 games
[ 06/15/2017 02:53:39 AM ] Starting game App 392870 to idle cards
[ 06/15/2017 02:53:39 AM ] App 392870 has 3 card drops remaining
[ 06/15/2017 02:53:39 AM ] Sleeping for 15 minutes
Loading Linux 64bit library
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
[S_API FAIL] SteamAPI_Init() failed; unable to locate a running instance of Steam, or a local steamclient.so.
Traceback (most recent call last):
  File "steam-idle.py", line 73, in <module>
    gui = init_gui(str_app_id)
  File "steam-idle.py", line 42, in init_gui
    gui = tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1813, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

```
Thanks for your help.

**Comment by xeiki** [comment]
Oh and here is the logfile:
```
[ 06/15/2017 01:56:06 PM ] Starting new HTTP connection (1): store.steampowered.com
[ 06/15/2017 01:56:06 PM ] "GET /api/appdetails/?appids=392870&filters=basic HTTP/1.1" 200 48
[ 06/15/2017 01:56:06 PM ] Checking to see if [36mApp 392870[39m has remaining card drops
[ 06/15/2017 01:56:06 PM ] Starting new HTTP connection (1): steamcommunity.com
[ 06/15/2017 01:56:07 PM ] "GET /profiles/76561198213659467/gamecards/392870/ HTTP/1.1" 302 20
[ 06/15/2017 01:56:07 PM ] "GET /id/_steam/gamecards/392870 HTTP/1.1" 200 8583
[ 06/15/2017 01:56:07 PM ] Starting new HTTP connection (1): store.steampowered.com
[ 06/15/2017 01:56:07 PM ] "GET /api/appdetails/?appids=392870&filters=basic HTTP/1.1" 200 48
[ 06/15/2017 01:56:07 PM ] [36mApp 392870[39m has 3 card drops remaining
[ 06/15/2017 01:56:07 PM ] Sleeping for 15 minutes
```

**Comment by ehne** [comment]
hello, just reading through your logs. It appears that you have not got steam running, idle master requires steam to be running for it to work

**Comment by cjmick** [comment]
I am having this same issue. I have stream running
